apiVersion: v1
kind: Service
metadata:
  name: framework
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 11000
  selector:
    app: framework
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framework
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: framework
    spec:
      containers:
      - name: framework
        image: 172.29.0.13:8082/framework:<BUILD_TAG>
        imagePullPolicy: Always
        volumeMounts:
        - name: time-zone
          mountPath: /etc/localtime
        - name: tomcat-logs
          mountPath: /usr/local/tomcat/logs
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: time-zone
        hostPath:
          path: /etc/localtime
      - name: tomcat-logs
        hostPath:
          path: /data/tomcat/logs