framework:
  app:
    home: /D/Projects/RunData/webim_home
  ip:
    enable: false
    topoptid: WebIm
    home: http://product.centit.com:8080/product-ip/service
    auth-enable: false
    usercode: admin
    password: 000000
